name: 'Get and cache dependencies'
description: 'Get the dependencies and cache them for later use'
inputs:
  caching:
    description: 'Do not use the cache'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: composite  
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies    
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      shell: bash
      run: npm ci