name: Create Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Get and cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Lint code
        run: npm run lint

      - name: Test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get and cache dependencies
        uses: ./.github/actions/cached-deps
      
      - name: Build
        run: npm run build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist


  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    steps:
          
      - name: Get code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      
      - name: Output contents
        run: ls -R

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Read version from package.json
          version=$(jq -r .version package.json)
 
          # Create the release using GitHub CLI
          gh release create "$version" \
            --title "Release $version" \
            --notes "Automated release for version $version" \
            --draft=false \
            --prerelease=false \
            dist

  cleanup_branch:
    name: Remove release branch
    needs: create_release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete release branch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/release/next-version'
            })
