name: Docker
on:
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    # Can only use images that are publicly available
    container: 
      image: node:18
      env:
        SOME_VAR: 'Moin'
    # Adding service containers
    services:
      ausweisapp:
        image: governikus/ausweisapp2
        ports:
          - 24727:24727
    steps:
      - name: Output GitHub Context
        run: echo "${{ toJson(github) }}"
      - name: Install wscat for WebSocket connection
        run: npm install -g wscat
      - name: Check AusweisApp2 status
        run: |
          echo "Checking AusweisApp2 status..."
                    wscat -c ws://ausweisapp:24727/eID-Kernel --headers "User-Agent: GitHub-Action-Check" -x '{"cmd": "GET_INFO"}'