name: Event Demo 1
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # This is also the default types config for pull_request
    types:
      - opened
      - synchronize
      - reopened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Data
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
