name: Matrix
on:
  workflow_dispatch:
jobs:
  build:
    # Setting this workflow won't stop executing because of one failure
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        runner: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build