name: Reusable
on:
  workflow_call:
    inputs:
      artifact:
        description: 'Name of the artifact to download'
        required: true
        type: string
        default: 'dist-files'
    outputs:
      result:
        description: 'The result of the workflow'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    # We have to define this output here, because we can't use the output from the step directly for the workflow output
    outputs:
      outcome: ${{ steps.set-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
      
      - name: Output contents
        run: ls

      - name: Deploy
        run: echo "Deploying..."
      
      - name: Set Result
        id: set-result
        run: echo "result=success" >> $GITHUB_ENV